# Setup Basic macros and known server names for reuse in scheduler files
spring:
  sleuth:
    trace-id128: true
  cloud:
    stream:
      bindings:
        output:
          destination: palindrome
          group: ${spring.application.name}
          contentType: application/json
        input:
          destination: palindrome
          group: ${spring.application.name}
          contentType: application/json
        kafka:
          bindings:
            input:
              consumer:
                enableDlq: true
      kafka:
        binder:
          brokers: ${kafka.brokers}
          autoCreateTopics: ${kafka.autoCreateTopics}
          autoAddPartitions: ${kafka.autoAddPartitions}
          minPartitionCount: ${kafka.minPartitionCount}
    config:
      fail-fast: false
      uri: http://localhost:8888
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      write-dates-as-timestamps: false
eureka:
  client:
    enabled: false
# Actuator info
info:
  project:
    name: "palindrome-service"
    description: "Parent pom providing dependency and plugin management for applications
		built with Maven"
    groupId: "org.springframework"
    artifactId: "palindrome-service"
    version: "0.1.0"
    owner: Flomdidumteam <Flomdidumteam@tdc.meow>
  build:
    maven: "3.3.9"
    time: "2019-07-07T10:55:00Z"
    git:
      commit: "@git.commit.id@"
      describe: "@git.commit.id.describe@"
    system:
      user: "m79932"
      os: "Windows 10/amd64"
    java:
      runtime: "Java(TM) SE Runtime Environment"
      vm: "Java HotSpot(TM) 64-Bit Server VM"
      version: "1.8.0_172"
  runtime:
    spring:
      profile: ${spring.profiles.active:default}
    system:
      user: ${user.name}
      os: ${os.name}/${os.arch}
    java:
      runtime: ${java.runtime.name}
      vm: ${java.vm.name}
      version: ${java.version}