/*
 * This file is generated by jOOQ.
 */
package palindrome.db.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import palindrome.db.jooq.Indexes;
import palindrome.db.jooq.Keys;
import palindrome.db.jooq.Public;
import palindrome.db.jooq.tables.records.PalindromedataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Palindromedata extends TableImpl<PalindromedataRecord> {

    private static final long serialVersionUID = -919834204;

    /**
     * The reference instance of <code>public.palindromedata</code>
     */
    public static final Palindromedata PALINDROMEDATA = new Palindromedata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PalindromedataRecord> getRecordType() {
        return PalindromedataRecord.class;
    }

    /**
     * The column <code>public.palindromedata.id</code>.
     */
    public final TableField<PalindromedataRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.palindromedata.payload</code>.
     */
    public final TableField<PalindromedataRecord, String> PAYLOAD = createField("payload", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.palindromedata.created_timestamp</code>.
     */
    public final TableField<PalindromedataRecord, Timestamp> CREATED_TIMESTAMP = createField("created_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>public.palindromedata</code> table reference
     */
    public Palindromedata() {
        this(DSL.name("palindromedata"), null);
    }

    /**
     * Create an aliased <code>public.palindromedata</code> table reference
     */
    public Palindromedata(String alias) {
        this(DSL.name(alias), PALINDROMEDATA);
    }

    /**
     * Create an aliased <code>public.palindromedata</code> table reference
     */
    public Palindromedata(Name alias) {
        this(alias, PALINDROMEDATA);
    }

    private Palindromedata(Name alias, Table<PalindromedataRecord> aliased) {
        this(alias, aliased, null);
    }

    private Palindromedata(Name alias, Table<PalindromedataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Palindromedata(Table<O> child, ForeignKey<O, PalindromedataRecord> key) {
        super(child, key, PALINDROMEDATA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PALINDROMEDATA_ID_UINDEX, Indexes.PALINDROMEDATA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PalindromedataRecord> getPrimaryKey() {
        return Keys.PALINDROMEDATA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PalindromedataRecord>> getKeys() {
        return Arrays.<UniqueKey<PalindromedataRecord>>asList(Keys.PALINDROMEDATA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Palindromedata as(String alias) {
        return new Palindromedata(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Palindromedata as(Name alias) {
        return new Palindromedata(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Palindromedata rename(String name) {
        return new Palindromedata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Palindromedata rename(Name name) {
        return new Palindromedata(name, null);
    }
}
