/*
 * This file is generated by jOOQ.
 */
package palindrome.db.jooq;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import palindrome.db.jooq.tables.Palindromedata;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PALINDROMEDATA_ID_UINDEX = Indexes0.PALINDROMEDATA_ID_UINDEX;
    public static final Index PALINDROMEDATA_PKEY = Indexes0.PALINDROMEDATA_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PALINDROMEDATA_ID_UINDEX = Internal.createIndex("palindromedata_id_uindex", Palindromedata.PALINDROMEDATA, new OrderField[] { Palindromedata.PALINDROMEDATA.ID }, true);
        public static Index PALINDROMEDATA_PKEY = Internal.createIndex("palindromedata_pkey", Palindromedata.PALINDROMEDATA, new OrderField[] { Palindromedata.PALINDROMEDATA.ID }, true);
    }
}
