/*
 * This file is generated by jOOQ.
 */
package palindrome.db.jooq;


import javax.annotation.Generated;

import palindrome.db.jooq.tables.Palindromedata;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.palindromedata</code>.
     */
    public static final Palindromedata PALINDROMEDATA = palindrome.db.jooq.tables.Palindromedata.PALINDROMEDATA;
}
